const PAGE_404 = 404;
const MIN_NUMBER_CARAC = 5;
const NAME_MIN_LENGTH = 12;
const USER_ALREADY_EXISTS = 409;
const UNAUTHORIZED = 401;

export default {
  PAGE_404,
  MIN_NUMBER_CARAC,
  NAME_MIN_LENGTH,
  USER_ALREADY_EXISTS,
  UNAUTHORIZED,
};
